[package]
name = "hanabi-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
rand = "0.8.5"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.26.1"
uuid = { version = "1.12.0", features = ["v4"] }
